# ~/.config/alacritty/alacritty.toml
# https://alacritty.org/config-alacritty.html

[window]
blur = false
opacity = 0.85
title = "Alacritty"
decorations = "None"
dynamic_title = true
dynamic_padding = true

[terminal]
shell = { program = "/usr/bin/fish", args = [ "--login", "--interactive" ] }

[general]
working_directory = "None"
live_config_reload = true

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t/"

[font]
size = 11.50
builtin_box_drawing = true
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
style = "Bold"
family = "Intel One Mono"

[font.bold]
style = "Bold"

[font.italic]
style = "Bold Italic"

[font.bold_italic]
style = "Bold Italic"

[cursor]
thickness = 0.20
blink_timeout = 10
blink_interval = 1000
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[colors]
# cursor = { cursor = "#ff1493" }
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#eaeaea"

[colors.normal]
black = "#000000"
blue = "#41b2f7"
cyan = "#32f8f4"
green = "#32f891"
magenta = "#f54bf9"
red = "#f94a4f"
white = "#eaeaea"
yellow = "#faf76e"

[colors.bright]
black = "#444444"
blue = "#41b2f7"
cyan = "#32f8f4"
green = "#32f891"
magenta = "#f54bf9"
red = "#f7191f"
white = "#ffffff"
yellow = "#f9f655"

# [terminal]
# shell = { program = "nu" }
# shell = { program = "pwsh" }
# shell = { program = "/bin/bash", args = [ "--login" ] }
# shell = { program = "/usr/bin/fish", args = [ "--login", "--interactive" ] }
# shell = { program = "C:\\Windows\\System32\\wsl.exe", args = [ "-d Arch", "-u wrx" ] }

# windows fixes
# [keyboard]
# bindings = [
#   # Fix <CTRL+Space>
#   { key = "Space", mods = "Control", chars = "\u0000" },
#   # Fix for <ALT+Enter>
#   { key = "Return", mods = "Alt", action = "ReceiveChar" },
#   # Fix for <ALT+Escape>
#   { key = "Escape", mods = "Alt", action = "ReceiveChar" },
#   # Fix <NumpadEnter>
#   { key = "NumpadEnter", mods = "None", action = "ReceiveChar" }
# ]
