# ~/.config/starship.toml
# -----------------------

[character]
error_symbol = "[âœ–](bold red)"
success_symbol = "[ğº](bold cyan)"

[username]
show_always = true
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style) on "

[hostname]
ssh_only = false
style = "bold dimmed green"
format = "[$hostname]($style) in "

[[battery.display]]
threshold = 15
style = "bold red"
discharging_symbol = 'ï‰ƒ  '
